// Paris Family Guide – zentrale Reisedaten
// Für künftige Änderungen hauptsächlich diese Datei bearbeiten.
window.TRIP_DATA = [
{
  date:'2026-09-12',label:'Sa',title:'Samstag · 12. September',note:'Heute bereits besucht: Quartier Latin und Odéon.',items:[
    {type:'stop',time:'13:38',duration:20,title:'Ankunft Gare de Lyon',icon:'🚄',fixed:true,subtitle:'Anreise und Start des Paris-Wochenendes',destination:'Gare de Lyon, Paris',infoTitle:'Gare de Lyon',info:`Der Gare de Lyon ist einer der grossen Pariser Kopfbahnhöfe. Seine heutige monumentale Gestalt entstand zur Weltausstellung von 1900. Besonders auffällig ist der rund 67 Meter hohe Uhrturm, der an einen italienischen Campanile erinnert.\n\nDer Bahnhof verbindet Paris traditionell mit Südostfrankreich, der Schweiz und Italien. Im Obergeschoss liegt mit Le Train Bleu zudem ein berühmtes Belle-Époque-Restaurant, dessen prunkvolle Säle ebenfalls um 1900 gestaltet wurden.`,look:'Der Uhrturm und die reich verzierte historische Fassade zeigen, wie repräsentativ Bahnhöfe um 1900 gebaut wurden.'},
    {type:'stop',time:'15:00',duration:120,title:'Quartier Latin & Odéon',icon:'✅',fixed:false,subtitle:'Bereits besucht · wird an den Folgetagen nicht wiederholt',destination:'Odéon, Paris',infoTitle:'Quartier Latin & Odéon',info:`Das Quartier Latin gehört zu den ältesten Bildungs- und Studentenvierteln von Paris. Sein Name geht auf das Latein zurück, das an der mittelalterlichen Universität gesprochen wurde. Rund um die Sorbonne, Saint-Germain und Odéon liegen bis heute Buchhandlungen, Cafés und Theater.\n\nDer Name Odéon verweist auf das Théâtre de l’Odéon, das Ende des 18. Jahrhunderts eröffnet wurde und zu den bedeutenden französischen Theaterhäusern zählt.`,look:'Das heutige Viertel wirkt lebendig und modern, doch sein Strassennetz und viele Institutionen erzählen von Jahrhunderten Pariser Bildungs- und Kulturgeschichte.'}
  ]
},
{
  date:'2026-09-13',label:'So',title:'Sonntag · 13. September',note:'Montmartre → Marais → Seine → Louvre. Der Nachmittag bleibt bewusst ohne zusätzlichen Pflichttermin.',items:[
    {type:'stop',time:'08:15',duration:30,title:'Frühstück im Hotel',icon:'☕',subtitle:'Ruhiger Start in den Tag',destination:'Novotel Paris Gare de Lyon, 2 Rue Hector Malot, Paris',infoTitle:'Tagesstart',info:`Heute verbindet ihr drei sehr unterschiedliche Seiten von Paris: das Künstler- und Wallfahrtsviertel Montmartre, den historischen Marais und anschliessend die Seine bis zum Louvre.\n\nDer Plan ist bewusst so aufgebaut, dass ihr am späteren Nachmittag keinen zusätzlichen Fixpunkt mehr habt. Wenn ihr müde seid, könnt ihr nach dem Louvre problemlos zurück ins Hotel.`,look:'Nehmt Wasser mit und tragt bequeme Schuhe – Montmartre hat spürbare Steigungen.'},
    {type:'route',time:'08:45',duration:35,title:'Hotel → Montmartre / Sacré-Cœur',icon:'🚇',mode:'transit',subtitle:'ÖV bis Montmartre, letzter Abschnitt zu Fuss',destination:'Basilique du Sacré-Cœur de Montmartre, Paris',routeText:'Praktisch ist die Fahrt ab Gare de Lyon Richtung Montmartre. Google Maps berücksichtigt die aktuelle Verbindung. Für den letzten Höhenunterschied könnt ihr Treppen oder die Standseilbahn nutzen.'},
    {type:'stop',time:'09:20',duration:45,title:'Sacré-Cœur',icon:'⛪',subtitle:'Basilika und Aussicht über Paris',destination:'Basilique du Sacré-Cœur de Montmartre, Paris',infoTitle:'Sacré-Cœur',info:`Die Basilika Sacré-Cœur steht auf dem höchsten natürlichen Punkt von Paris. Ihr Bau wurde nach dem Deutsch-Französischen Krieg von 1870/71 beschlossen und war zugleich religiöses Projekt und nationales Symbol. Der Grundstein wurde 1875 gelegt; vollendet wurde die Kirche erst zu Beginn des 20. Jahrhunderts.\n\nAuffällig ist der helle Travertin aus Château-Landon. Dieser Stein setzt bei Regen Calcit frei und bleibt dadurch ungewöhnlich weiss. Im Innern befindet sich eines der grössten Mosaike Frankreichs: Christus mit ausgebreiteten Armen über dem Chor.\n\nMontmartre war vor seiner Eingemeindung 1860 ein eigenständiger Ort ausserhalb der Pariser Steuergrenzen. Später zog das Viertel Künstler wie Renoir, Toulouse-Lautrec, Picasso und Modigliani an.`,look:'Schaut von der Treppe aus nach Süden: Ihr erkennt, wie flach grosse Teile von Paris sind. Der Eiffelturm liegt von hier aus seitlich und ist nicht das einzige dominierende Bauwerk.'},
    {type:'route',time:'10:05',duration:5,title:'Sacré-Cœur → Place du Tertre',icon:'🚶',mode:'walking',subtitle:'Kurzer Weg durch die kleinen Strassen von Montmartre',destination:'Place du Tertre, Paris',routeText:'Nur wenige Minuten zu Fuss. Achtet auf das Kopfsteinpflaster und die schmalen Gassen – hier ändert sich die Atmosphäre sofort von Wallfahrtsort zu Künstlerquartier.'},
    {type:'stop',time:'10:10',duration:30,title:'Place du Tertre',icon:'🎨',subtitle:'Künstlerplatz im Herzen von Montmartre',destination:'Place du Tertre, Paris',infoTitle:'Place du Tertre',info:`Der kleine Platz liegt nur wenige Schritte von Sacré-Cœur entfernt und erinnert an die Zeit, in der Montmartre ein Dorf war. Das frühere Rathaus von Montmartre lag hier in unmittelbarer Nähe.\n\nHeute arbeiten auf dem Platz zahlreiche zugelassene Maler und Porträtisten. Das wirkt touristisch, führt aber eine echte Tradition fort: Ende des 19. und Anfang des 20. Jahrhunderts lebten und arbeiteten in Montmartre viele Künstler, weil Ateliers und Wohnungen hier günstiger waren als im Zentrum.\n\nIn der Umgebung lagen berühmte Treffpunkte der Avantgarde. Picasso malte im Bateau-Lavoir wenige hundert Meter entfernt an Werken, die später den Kubismus prägten.`,look:'Beobachtet, wie unterschiedlich die Künstler Gesichter oder Pariser Motive interpretieren. Ein Porträt ist nicht einfach eine Kopie – jeder zeichnet anders.'},
    {type:'route',time:'10:40',duration:15,title:'Place du Tertre → Boris Lumé',icon:'🚶',mode:'walking',subtitle:'Bergab Richtung Rue Caulaincourt',destination:'Boris Lumé Boulangerie, 48 Rue Caulaincourt, Paris',routeText:'Der Weg führt durch typische Montmartre-Strassen. Plant etwas Reserve ein, weil es stellenweise Treppen und Gefälle gibt.'},
    {type:'stop',time:'10:55',duration:30,title:'Boris Lumé – „Ladybug-Bäckerei“',icon:'🥐',subtitle:'48 Rue Caulaincourt · Inspiration für Miraculous-Fans',destination:'Boris Lumé Boulangerie, 48 Rue Caulaincourt, Paris',infoTitle:'Boris Lumé und Miraculous',info:`Die Bäckerei Boris Lumé an der Rue Caulaincourt wird von Fans häufig mit der Bäckerei der Familie Dupain-Cheng aus „Miraculous – Geschichten von Ladybug und Cat Noir“ in Verbindung gebracht. Die Serie verwendet reale Pariser Orte und kombiniert sie mit erfundenen Gebäuden und Adressen.\n\nWichtig: Die Bäckerei in der Serie ist kein eins zu eins reales Gebäude. Der Besuch ist deshalb eher ein spielerischer Vergleich zwischen echtem Paris und der animierten Welt.\n\nUnabhängig davon ist die Adresse ein guter Zwischenhalt für ein Croissant, Pain au chocolat oder etwas Herzhaftes, bevor ihr Montmartre verlasst.`,look:'Vergleicht Fassade, Fenster und Umgebung mit dem Stil aus Miraculous. Welche Details könnten die Zeichner übernommen oder verändert haben?'},
    {type:'route',time:'11:25',duration:40,title:'Montmartre → Marché des Enfants Rouges',icon:'🚇',mode:'transit',subtitle:'Weiter ins Marais',destination:'Marché des Enfants Rouges, 39 Rue de Bretagne, Paris',routeText:'Mit Metro/Bus Richtung Marais. Google Maps wählt die aktuell schnellste Verbindung. Ziel ist die Rue de Bretagne im 3. Arrondissement.'},
    {type:'stop',time:'12:05',duration:80,title:'Marché des Enfants Rouges & Mittagessen',icon:'🥙',subtitle:'Historischer Markt · sonntags 08:30–17:00',destination:'Marché des Enfants Rouges, 39 Rue de Bretagne, Paris',infoTitle:'Marché des Enfants Rouges',info:`Der Marché des Enfants Rouges wurde 1615 gegründet und gilt als ältester noch betriebener überdachter Lebensmittelmarkt von Paris. Sein ungewöhnlicher Name – „Markt der roten Kinder“ – geht auf ein benachbartes Waisenhaus zurück. Die Kinder dort trugen rote Kleidung als Zeichen christlicher Nächstenliebe.\n\nDer Markt ist heute eine Mischung aus klassischem Lebensmittelmarkt und kleinem Food-Court. Zwischen Gemüse, Käse und Blumen findet ihr marokkanische, französische, italienische, japanische und afro-karibische Küche.\n\nFür euch ist das ideal: Jeder kann etwas anderes wählen, und das Mittagessen ist gleichzeitig Teil der Sehenswürdigkeit.`,look:'Schaut nicht nur auf das Essen. Die engen Marktgänge und die niedrige Struktur zeigen, wie anders ein historischer Quartiermarkt funktioniert als ein moderner Supermarkt.',restaurants:[
      {name:'Le Traiteur Marocain',meta:'Marokkanisch · unkompliziert · €',text:'Couscous und Tajine direkt im Markt. Gute Familienoption, wenn ihr etwas Warmes und Herzhaftes möchtet.',map:'Le Traiteur Marocain, 39 Rue de Bretagne, Paris'},
      {name:'Chez Alain Miam Miam',meta:'XXL-Sandwiches & Galettes · €€',text:'Berühmt für sehr grosszügig belegte Sandwiches. Oft Warteschlange; eher wählen, wenn ihr Lust auf Streetfood und etwas Geduld habt.',map:'Chez Alain Miam Miam, 26 Rue Charlot, Paris'},
      {name:'Corossol',meta:'Afro-karibisch · Marktstand',text:'Eine farbenfrohe Alternative mit kamerunisch/antillisch geprägter Küche. Gut, wenn ihr etwas anderes als klassische französische Küche ausprobieren möchtet.',map:'Marché des Enfants Rouges, 39 Rue de Bretagne, Paris'}
    ]},
    {type:'route',time:'13:25',duration:30,title:'Marché → Pont Marie',icon:'🚶',mode:'walking',subtitle:'Zu Fuss durch den Marais Richtung Seine',destination:'Pont Marie, Paris',routeText:'Der Weg führt quer durch den Marais. Nehmt nicht zwingend die schnellste Route – die kleinen Strassen gehören hier zum Erlebnis. Ziel ist Pont Marie an der Seine.'},
    {type:'stop',time:'13:55',duration:15,title:'Pont Marie',icon:'🌉',subtitle:'Startpunkt eures Seine-Spaziergangs',destination:'Pont Marie, Paris',infoTitle:'Pont Marie und die Seine',info:`Der Pont Marie wurde im 17. Jahrhundert gebaut und gehört zu den älteren Steinbrücken von Paris. Er verbindet das rechte Seineufer mit der Île Saint-Louis. Benannt ist er nach dem Unternehmer Christophe Marie, der an der Erschliessung der Insel beteiligt war.\n\nDie Seine war über Jahrhunderte Verkehrsweg, Handelsachse und natürliche Orientierungslinie der Stadt. Viele der wichtigsten Pariser Monumente stehen bewusst am Fluss.`,look:'Stellt euch vor, dass auf Pariser Brücken früher teilweise Häuser standen. Brücken waren nicht nur Verkehrswege, sondern konnten dicht bebaute Stadträume sein.'},
    {type:'route',time:'14:10',duration:50,title:'Seine-Spaziergang Pont Marie → Louvre',icon:'🚶',mode:'walking',subtitle:'Mit Fotostopps entlang des Flusses',destination:'Musée du Louvre, Paris',routeText:'Folgt der Seine westwärts Richtung Louvre. Unterwegs habt ihr Ausblicke auf die Île de la Cité, historische Brücken und die Uferbebauung. Die angegebene Zeit enthält bewusst kleine Stopps.'},
    {type:'stop',time:'15:00',duration:45,title:'Louvre & Pyramide – von aussen',icon:'🔺',subtitle:'Kein Museumsbesuch · Architektur und Geschichte',destination:'Pyramide du Louvre, Paris',infoTitle:'Louvre und Pyramide',info:`Der Louvre begann nicht als Museum, sondern als mittelalterliche Festung. König Philippe Auguste liess um 1190 eine Befestigung am Seineufer errichten. Später wurde daraus ein königlicher Palast, der über Jahrhunderte immer wieder erweitert wurde.\n\n1793, während der Französischen Revolution, wurde im Louvre ein öffentliches Museum eröffnet. Heute zählt er zu den grössten und bekanntesten Museen der Welt. Die berühmte Glaspyramide im Cour Napoléon kam jedoch erst 1989 hinzu. Sie wurde vom chinesisch-amerikanischen Architekten I. M. Pei entworfen und war zunächst heftig umstritten.\n\nDie Pyramide löste zugleich ein praktisches Problem: Sie schuf einen klaren zentralen Eingang für den riesigen Museumskomplex unter dem historischen Hof. Alt und Neu stehen hier sehr bewusst nebeneinander.`,look:'Sucht die Spiegelungen des historischen Palasts in den Glasflächen der Pyramide. Je nach Standort wirkt die moderne Form plötzlich wie ein Teil der alten Fassaden.'},
    {type:'stop',time:'15:45',duration:90,title:'Freier Nachmittag',icon:'✨',optional:true,subtitle:'Palais Royal, Café oder Rückfahrt ins Hotel – spontan entscheiden',destination:'Palais Royal, Paris',infoTitle:'Bewusster Freiraum',info:`Nach einem langen Vormittag und frühen Nachmittag bleibt jetzt Zeit für eine spontane Entscheidung. Ihr könnt kurz zum Palais Royal gehen, einen Kaffee oder ein Eis nehmen oder direkt ins Hotel zurückfahren.\n\nDieser Block ist absichtlich optional. Die Reise soll nicht zu einer Liste werden, die unbedingt abgearbeitet werden muss.`,look:'Wenn die Kinder noch Energie haben, sind die schwarz-weissen Säulen im Innenhof des Palais Royal ein spielerischer Fotostopp.'}
  ]
},
{
  date:'2026-09-14',label:'Mo',title:'Montag · 14. September',note:'Der Eiffelturm um 17:00 ist der zentrale Fixtermin. Der Arc-Aufstieg ist eingeplant, wird bei Verzug aber als Erstes gestrichen.',items:[
    {type:'stop',time:'09:00',duration:35,title:'Frühstück im Hotel',icon:'☕',subtitle:'Genug Zeit für einen ruhigen Start',destination:'Novotel Paris Gare de Lyon, 2 Rue Hector Malot, Paris',infoTitle:'Montag vorbereiten',info:`Heute arbeitet der ganze Tagesplan auf den Eiffelturm um 17:00 hin. Die wichtigsten Sicherheitsreserven liegen am Nachmittag.\n\nDer Aufstieg auf den Arc de Triomphe ist eingeplant, aber bewusst als optionale Aktivität markiert. Wenn ihr Verspätung habt, fällt zuerst dieser Aufstieg weg – nicht der Trocadéro-Puffer und nicht die Sicherheitszeit am Eiffelturm.`,look:'Tickets und Ausweise für den Eiffelturm am Morgen schon griffbereit einpacken.'},
    {type:'route',time:'09:45',duration:30,title:'Hotel → Printemps Haussmann',icon:'🚇',mode:'transit',subtitle:'Richtung Boulevard Haussmann',destination:'Printemps Haussmann, 64 Boulevard Haussmann, Paris',routeText:'Fahrt mit dem ÖV Richtung Opéra/Haussmann. Ziel ist Printemps Femme am Boulevard Haussmann.'},
    {type:'stop',time:'10:15',duration:60,title:'Printemps Haussmann & Dachterrasse',icon:'🏙️',subtitle:'Terrasse du 7ème Ciel · 7. Stock · Montag 10:00–20:00',destination:'Printemps Haussmann, 64 Boulevard Haussmann, Paris',infoTitle:'Printemps Haussmann',info:`Printemps wurde 1865 von Jules Jaluzot und Jean-Alfred Duclos gegründet. Das Warenhaus entstand in einer Zeit, in der Baron Haussmann Paris mit breiten Boulevards, neuen Bahnhöfen und modernen Geschäftsvierteln grundlegend umgestaltete.\n\nDie grossen Pariser Warenhäuser waren mehr als Einkaufsläden: Sie führten neue Verkaufskonzepte, feste Preise, Schaufensterinszenierungen und spektakuläre Architektur ein. Printemps brannte mehrfach teilweise aus und wurde jeweils modern wiederaufgebaut. Berühmt sind seine Kuppeln und Jugendstil-Elemente.\n\nDie Terrasse „7ème Ciel“ im Printemps Femme bietet einen weiten Blick über die Dächer. Anders als beim Eiffelturm erlebt ihr hier die Stadt auf Höhe der typischen Haussmann-Dächer.`,look:'Sucht von oben die Opéra Garnier und die charakteristischen grauen Zinkdächer. Diese Dächer prägen das Bild von Paris fast ebenso stark wie die grossen Monumente.'},
    {type:'route',time:'11:15',duration:25,title:'Printemps → Place de la Concorde',icon:'🚶',mode:'walking',subtitle:'Über das Haussmann-/Madeleine-Viertel',destination:'Place de la Concorde, Paris',routeText:'Zu Fuss Richtung Place de la Concorde. Ihr kommt dabei durch das elegante Zentrum rund um Madeleine und Rue Royale.'},
    {type:'stop',time:'11:40',duration:25,title:'Place de la Concorde',icon:'🏛️',subtitle:'Obelisk, Stadtachsen und Revolutionsgeschichte',destination:'Place de la Concorde, Paris',infoTitle:'Place de la Concorde',info:`Der Platz entstand im 18. Jahrhundert zunächst als Place Louis XV. Während der Französischen Revolution wurde er zur Place de la Révolution – und hier stand die Guillotine, an der unter anderem König Louis XVI und Marie-Antoinette hingerichtet wurden.\n\nIn der Mitte steht heute der mehr als 3'000 Jahre alte Obelisk von Luxor. Ägypten schenkte Frankreich im 19. Jahrhundert zwei Obelisken; tatsächlich wurde nur einer nach Paris transportiert.\n\nStädtebaulich ist der Platz ein Scharnier: Nach Westen beginnen die Champs-Élysées, nach Osten schliessen die Tuilerien an, nach Norden führt die Rue Royale zur Madeleine.`,look:'Stellt euch in die Achse Champs-Élysées–Arc de Triomphe. Ihr seht, wie Paris grosse Monumente bewusst auf langen Sichtlinien anordnet.'},
    {type:'stop',time:'12:05',duration:60,title:'Mittagessen',icon:'🍴',subtitle:'In der Gegend Concorde / Champs-Élysées',destination:'Place de la Concorde, Paris',infoTitle:'Mittagspause',info:`Die Mittagspause ist bewusst flexibel. Der Nachmittag hat mit Arc de Triomphe, Trocadéro und Eiffelturm genug Programm.\n\nWenn ihr beim Essen länger sitzen möchtet, ist das möglich – bei Verspätung wird später zuerst der Arc-Aufstieg gekürzt oder ganz ausgelassen.`,look:'Lieber eine ruhige Stunde essen als hastig mehrere Sehenswürdigkeiten abhaken.'},
    {type:'route',time:'13:05',duration:35,title:'Concorde → Champs-Élysées → Arc de Triomphe',icon:'🚶',mode:'walking',subtitle:'Nur einen ausgewählten Abschnitt zu Fuss, Rest bei Bedarf mit Métro 1',destination:'Arc de Triomphe, Place Charles de Gaulle, Paris',routeText:'Geht zunächst den unteren Abschnitt der Champs-Élysées entlang. Wenn ihr genug davon gesehen habt, könnt ihr ab Franklin D. Roosevelt mit der Métro 1 bis Charles de Gaulle–Étoile fahren. So erlebt ihr die Avenue, ohne die ganze Strecke laufen zu müssen.'},
    {type:'stop',time:'13:40',duration:20,title:'Arc de Triomphe – aussen',icon:'🏛️',subtitle:'Pflichtteil · Place Charles de Gaulle',destination:'Arc de Triomphe, Place Charles de Gaulle, Paris',infoTitle:'Arc de Triomphe',info:`Napoleon gab den Arc de Triomphe 1806 nach seinem Sieg bei Austerlitz in Auftrag. Vollendet wurde er erst 1836, lange nach dem Ende seiner Herrschaft. Der Bogen erinnert an französische Armeen und militärische Siege; Namen von Generälen und Schlachten sind in die Flächen eingraviert.\n\nUnter dem Bogen liegt seit 1921 das Grabmal des Unbekannten Soldaten aus dem Ersten Weltkrieg. Die Ewige Flamme wird täglich neu entzündet und macht den Ort zu einem zentralen nationalen Erinnerungsort Frankreichs.\n\nVon der Terrasse erkennt man besonders gut den sternförmigen Stadtgrundriss: Zwölf grosse Avenuen laufen auf die Place Charles de Gaulle zu. Diese Ordnung wurde im 19. Jahrhundert unter Napoleon III und Haussmann ausgebaut.`,look:'Nicht über den Kreisverkehr laufen. Der sichere Zugang zum Monument erfolgt durch die Unterführung. Auf dem Platz erkennt ihr die zwölf strahlenförmig angeordneten Avenuen.'},
    {type:'stop',time:'14:00',duration:60,title:'OPTION: Aufstieg auf den Arc de Triomphe',icon:'⬆️',optional:true,dropIfDelay:15,subtitle:'Terrasse · ca. 45–60 Min. · bei Zeitdruck auslassen',destination:'Arc de Triomphe, Place Charles de Gaulle, Paris',infoTitle:'Terrasse des Arc de Triomphe',info:`Die Terrasse bietet einen der besten Stadtblicke für das Verständnis des Pariser Stadtplans. Anders als vom Eiffelturm seid ihr mitten in der grossen historischen Achse: Champs-Élysées und Louvre liegen in der einen Richtung, La Défense mit der Grande Arche in der anderen.\n\nDer klassische Aufstieg erfolgt über 284 Stufen. Im Innern gibt es einen Ausstellungsbereich, bevor ihr die Dachterrasse erreicht. Für Kinder unter 18 ist der Eintritt grundsätzlich kostenlos; Erwachsene benötigen ein Ticket.\n\nDiese Aktivität ist bewusst optional. Bei mehr als ungefähr 15 Minuten Verspätung empfiehlt der Guide, den Aufstieg zu streichen und nach dem Aussenbesuch direkt zum Trocadéro weiterzufahren.`,look:'Oben die gerade Linie Louvre – Champs-Élysées – Arc – La Défense suchen. Diese sogenannte historische Achse verbindet mehrere Jahrhunderte Pariser Stadtentwicklung.'},
    {type:'route',time:'15:00',duration:25,title:'Arc de Triomphe → Trocadéro',icon:'🚇',mode:'transit',subtitle:'Kurze Fahrt Richtung Eiffelturm',destination:'Place du Trocadéro et du 11 Novembre, Paris',routeText:'Am einfachsten mit Métro 6 ab Charles de Gaulle–Étoile bis Trocadéro. Damit kommt ihr direkt zu einem der klassischen Aussichtspunkte auf den Eiffelturm.'},
    {type:'stop',time:'15:25',duration:30,title:'Trocadéro',icon:'📸',subtitle:'Fotos, Aussicht und kurze Pause',destination:'Place du Trocadéro et du 11 Novembre, Paris',infoTitle:'Trocadéro',info:`Der heutige Palais de Chaillot entstand für die Weltausstellung von 1937. Seine beiden geschwungenen Flügel rahmen bewusst den Blick auf den Eiffelturm. Der freie Raum dazwischen ist eine der bekanntesten Fotoperspektiven von Paris.\n\nDer Name Trocadéro erinnert an eine französische Militäraktion von 1823 bei Cádiz in Spanien. Vor dem heutigen Palais stand ein älterer, deutlich exotischer gestalteter Bau der Weltausstellung von 1878.\n\nVon hier aus versteht man auch die Inszenierung des Eiffelturms: Zwischen Chaillot und Champ-de-Mars wird der Turm wie auf einer städtischen Bühne präsentiert.`,look:'Probiert ein Foto, bei dem der Eiffelturm genau zwischen den beiden Flügeln des Palais de Chaillot steht.'},
    {type:'route',time:'15:55',duration:25,title:'Trocadéro → Eiffelturm-Eingang',icon:'🚶',mode:'walking',fixed:true,subtitle:'Nicht mehr trödeln · über Pont d’Iéna zum Ticketzugang',destination:'Eiffel Tower, Paris',routeText:'Jetzt beginnt der feste Zeitpuffer. Geht über den Pont d’Iéna zu den Eingängen in den Gärten. Folgt der Beschilderung für Besucher mit Ticket.'},
    {type:'stop',time:'16:20',duration:40,title:'Sicherheitskontrolle & Einlasspuffer',icon:'🛂',fixed:true,subtitle:'Spätestens jetzt am Eiffelturm sein',destination:'Eiffel Tower, Paris',infoTitle:'Eiffelturm – Einlass',info:`Eure Tickets gelten für 17:00 und führen mit dem Lift bis zur Spitze. Für die Sicherheitskontrollen solltet ihr 15–20 Minuten einplanen; mit Kindern ist ein zusätzlicher Puffer sinnvoll.\n\nGrosse Gepäckstücke können nicht deponiert werden. Haltet Tickets und allfällige Alters-/Identitätsnachweise griffbereit. Wer zu spät kommt, hat keinen garantierten Einlass.`,look:'Ab jetzt keine zusätzlichen Stopps mehr einbauen. Der Puffer schützt euren wichtigsten Fixtermin des Tages.'},
    {type:'stop',time:'17:00',duration:150,title:'Eiffelturm – Spitze mit Lift',icon:'🗼',fixed:true,subtitle:'FIX · Tickets vorhanden · bis ca. 19:30',destination:'Eiffel Tower, Paris',infoTitle:'Eiffelturm',info:`Der Eiffelturm wurde für die Weltausstellung von 1889 errichtet, die zugleich an den 100. Jahrestag der Französischen Revolution erinnerte. Ingenieur Gustave Eiffel übernahm das Projekt, dessen konstruktive Planung wesentlich von Maurice Koechlin und Émile Nouguier entwickelt worden war.\n\nMit rund 300 Metern war der Turm bei seiner Fertigstellung das höchste Bauwerk der Welt. Viele Künstler und Schriftsteller protestierten zunächst gegen die „nutzlose und monströse“ Eisenkonstruktion. Gerade diese sichtbare Tragstruktur wurde später zum Symbol moderner Ingenieurskunst.\n\nDer Turm war ursprünglich nicht als dauerhaftes Bauwerk gedacht. Seine Bedeutung für Funk- und Telegraphieversuche half, ihn zu erhalten. Heute wird die Höhe durch Antennen auf über 330 Meter gesteigert.\n\nEure Route: Lift vom Boden zur 2. Etage, dort Umstieg auf den Lift zur Spitze. Beim Abstieg könnt ihr die 2. und 1. Etage noch in Ruhe ansehen.`,look:'An der Spitze nach dem Verlauf der Seine suchen. Auf der 2. Etage sind einzelne Monumente oft leichter zu erkennen als ganz oben, weil ihr näher an der Stadt seid.'},
    {type:'route',time:'19:30',duration:15,title:'Eiffelturm → Abendessen',icon:'🚶',mode:'walking',subtitle:'Keine Seinefahrt mehr · gemütlich essen',destination:'Rue Cler, Paris',routeText:'Nach dem Turm geht ihr ohne weiteren Termin zum Abendessen. Die Vorschläge liegen im 7. Arrondissement und sind zu Fuss oder mit einer sehr kurzen Fahrt erreichbar.'},
    {type:'restaurant',time:'19:45',duration:90,title:'Gemütliches Abendessen',icon:'🍽️',subtitle:'Drei Varianten – je nach Lust, Hunger und Energie',destination:'Rue Cler, Paris',infoTitle:'Abendessen nach dem Eiffelturm',info:`Nach dem Eiffelturm ist bewusst kein weiteres Sightseeing mehr geplant. Ziel ist ein gutes, entspanntes Abendessen, bei dem ihr den Tag ausklingen lassen könnt.\n\nDie drei Vorschläge decken unterschiedliche Stimmungen ab: klassisch-pariserisch und unkompliziert, familienfreundliche Crêpes oder etwas ambitioniertere französische Küche.`,look:'Wenn ihr beim Eiffelturm länger bleibt, nehmt die unkompliziertere Option mit langen Öffnungszeiten.',restaurants:[
      {name:'Le Petit Cler',meta:'Französisches Bistro · €€ · täglich bis 24:00',text:'Mein unkomplizierter Favorit für euch: klassische Bistrogerichte, gemütlich, kinderfreundlich und mit langer Öffnungszeit. Gute Wahl, wenn ihr erst gegen 20:00 oder später loskommt.',map:'Le Petit Cler, 29 Rue Cler, Paris'},
      {name:'Breizh Café Rue Cler',meta:'Galettes & Crêpes · €€ · Montag bis 22:30',text:'Sehr familienfreundlich und nach einem langen Tag angenehm unkompliziert. Herzhafte Buchweizengalettes und süsse Crêpes; auch vegetarische Optionen.',map:'Breizh Café Rue Cler, 59 Rue Cler, Paris'},
      {name:"L'Escudella",meta:'Moderne französische Küche · €€€ · Abendservice ca. 19:00–21:15',text:'Die besondere Variante für ein etwas feineres Abendessen. Kleine, ruhige Adresse; Reservation ist hier sinnvoll. Nur wählen, wenn ihr rechtzeitig vom Eiffelturm herunterkommt.',map:"L'Escudella, 41 Avenue de Ségur, Paris"}
    ]}
  ]
},
{
  date:'2026-09-15',label:'Di',title:'Dienstag · 15. September',note:'Letzter Vormittag direkt rund um Hotel und Gare de Lyon. Keine weiten Wege mehr.',items:[
    {type:'stop',time:'08:00',duration:45,title:'Frühstück & Check-out',icon:'☕',subtitle:'Gepäck anschliessend im Hotel lassen',destination:'Novotel Paris Gare de Lyon, 2 Rue Hector Malot, Paris',infoTitle:'Abreisetag',info:`Der letzte Vormittag bleibt bewusst in der Nähe des Hotels. Ihr müsst nicht mehr quer durch Paris fahren und habt dadurch einen entspannten Sicherheitsabstand zum TGV.`,look:'Vor dem Verlassen des Zimmers Ladegeräte, Tickets, Ausweise und Kinder-Sachen kontrollieren.'},
    {type:'route',time:'08:45',duration:15,title:'Hotel → Marché d’Aligre',icon:'🚶',mode:'walking',subtitle:'Kurzer Weg ins Quartier',destination:"Marché d'Aligre, Place d'Aligre, Paris",routeText:'Zu Fuss vom Hotel Richtung Rue d’Aligre. Der Markt liegt nur eine kurze Strecke vom Gare-de-Lyon-Viertel entfernt.'},
    {type:'stop',time:'09:00',duration:75,title:'Marché d’Aligre & Beauvau',icon:'🍎',subtitle:'Dienstag: Markt 07:30–13:30 · Halle 08:00–13:00',destination:"Marché d'Aligre, Place d'Aligre, Paris",infoTitle:'Marché d’Aligre',info:`Der Marché d’Aligre ist weniger monumental als die grossen Sehenswürdigkeiten – gerade deshalb ist er interessant. Hier erlebt ihr einen lebendigen Quartiermarkt mit Obst, Gemüse, Käse, Blumen und Haushaltswaren. Direkt daneben liegt der überdachte Marché Beauvau.\n\nDas Viertel entstand rund um die ehemalige Abtei Saint-Antoine und entwickelte sich zu einem Handels- und Handwerkergebiet. Bis heute ist Aligre für seine vergleichsweise ungezwungene, lokale Atmosphäre bekannt.\n\nFür die Rückfahrt könnt ihr hier noch Obst, Gebäck oder kleine Snacks einkaufen.`,look:'Vergleicht den offenen Strassenmarkt mit dem überdachten Marché Beauvau – zwei sehr unterschiedliche Marktformen direkt nebeneinander.'},
    {type:'route',time:'10:15',duration:15,title:'Aligre → Coulée Verte René-Dumont',icon:'🚶',mode:'walking',subtitle:'Zum erhöhten Grünweg auf dem Viaduc des Arts',destination:'Coulée Verte René-Dumont, Paris',routeText:'Geht Richtung Avenue Daumesnil und sucht einen der Aufgänge zur Coulée Verte. Von dort folgt ihr dem erhöhten Weg in Richtung Bastille.'},
    {type:'stop',time:'10:30',duration:75,title:'Coulée Verte René-Dumont',icon:'🌿',subtitle:'Ehemalige Bahntrasse · am 15.09. ab 07:00 geöffnet',destination:'Coulée Verte René-Dumont, Paris',infoTitle:'Coulée Verte René-Dumont',info:`Die Coulée Verte entstand auf der Trasse einer Eisenbahnlinie, die seit dem 19. Jahrhundert den damaligen Bahnhof Bastille mit dem Osten der Region verband. Nach Stilllegung der Strecke wurde ein Teil in den 1980er- und 1990er-Jahren zu einer begrünten Promenade umgebaut.\n\nBesonders spannend ist der Abschnitt auf dem Viaduc des Arts: Ihr spaziert mehrere Meter über dem Strassenniveau, während in den restaurierten Bögen darunter Werkstätten, Ateliers und Geschäfte liegen.\n\nDas Konzept war international wegweisend. Spätere Projekte wie die High Line in New York werden häufig mit dieser Pariser Promenade verglichen.`,look:'Schaut über die Brüstungen in die Strassen hinunter. Durch die erhöhte Perspektive entdeckt ihr Balkone, Hinterhöfe und Dächer, die man vom Gehsteig kaum wahrnimmt.'},
    {type:'route',time:'11:45',duration:15,title:'Coulée Verte → Bastille',icon:'🚶',mode:'walking',subtitle:'Richtung Place de la Bastille',destination:'Place de la Bastille, Paris',routeText:'Geht in Richtung Bastille und Opéra Bastille. Damit endet der Spaziergang wieder in einem lebendigen Stadtquartier.'},
    {type:'stop',time:'12:00',duration:20,title:'Place de la Bastille',icon:'🇫🇷',subtitle:'Kurzer historischer Halt',destination:'Place de la Bastille, Paris',infoTitle:'Bastille',info:`Auf dem heutigen Platz stand einst die Bastille, eine mittelalterliche Festung und später ein Staatsgefängnis. Ihr Sturm am 14. Juli 1789 wurde zum Symbol der Französischen Revolution – obwohl zu diesem Zeitpunkt nur wenige Gefangene darin sassen.\n\nDie Festung wurde kurz nach der Revolution fast vollständig abgebrochen. In der Mitte des Platzes steht heute die Julisäule, die jedoch nicht an 1789, sondern an die Revolution von 1830 erinnert.\n\nDie moderne Opéra Bastille wurde 1989 zum 200. Jahrestag der Französischen Revolution eröffnet.`,look:'Von der ursprünglichen Festung ist oberirdisch fast nichts mehr vorhanden. Achtet auf Markierungen im Boden, die den früheren Verlauf andeuten.'},
    {type:'restaurant',time:'12:20',duration:70,title:'Mittagessen vor der Rückfahrt',icon:'🍴',subtitle:'Bastille / Gare de Lyon – ohne Stress',destination:'Bastille, Paris',infoTitle:'Letztes Mittagessen in Paris',info:`Für den letzten Lunch würde ich etwas wählen, das unkompliziert ist und euch nicht weit vom Hotel wegführt. Danach bleibt genügend Zeit für Gepäck und Bahnhof.`,look:'Spätestens gegen 13:30 solltet ihr wieder Richtung Hotel gehen.',restaurants:[
      {name:'Petit Bao Bastille',meta:'Chinesisch / Dim Sum · €€ · Dienstag Mittag',text:'Sehr lebendig, familienfreundlich und etwas ganz anderes als klassische Bistroküche. Ideal für Dumplings, Bao und mehrere Gerichte zum Teilen.',map:'Petit Bao Bastille, 10 Rue Bréguet, Paris'},
      {name:'Le Train Bleu',meta:'Französisch · €€€ · Gare de Lyon',text:'Die besondere historische Variante direkt im Bahnhof. Prächtige Belle-Époque-Säle – eher Erlebnisrestaurant als schneller Lunch. Nur wählen, wenn ihr reserviert und genügend Zeit lassen wollt.',map:'Le Train Bleu, Gare de Lyon, Paris'},
      {name:'Café rund um Rue de Lyon',meta:'Flexibel · €–€€',text:'Wenn ihr spontan bleiben wollt, nehmt einfach ein Café oder eine Brasserie auf dem Weg Richtung Hotel. Das ist die sicherste Variante für einen entspannten Abreisetag.',map:'Rue de Lyon, Paris'}
    ]},
    {type:'route',time:'13:30',duration:15,title:'Zurück zum Hotel',icon:'🚶',mode:'walking',subtitle:'Gepäck abholen',destination:'Novotel Paris Gare de Lyon, 2 Rue Hector Malot, Paris',routeText:'Direkt zurück zum Novotel. Ab jetzt nichts Neues mehr einplanen.'},
    {type:'stop',time:'13:45',duration:45,title:'Gepäck holen & kurze Pause',icon:'🧳',subtitle:'Toilette, Wasser, Tickets prüfen',destination:'Novotel Paris Gare de Lyon, 2 Rue Hector Malot, Paris',infoTitle:'Rückreise vorbereiten',info:`Nutzt den Zeitpuffer für Gepäck, Toilette, Wasser und eine letzte Kontrolle. So beginnt die Rückfahrt ohne Hektik.`,look:'TGV-Tickets, Wagen- und Sitzplatznummern nochmals prüfen.'},
    {type:'route',time:'14:30',duration:15,title:'Hotel → Gare de Lyon',icon:'🚶',mode:'walking',fixed:true,subtitle:'Sehr kurze Strecke · mit Gepäck langsam gehen',destination:'Gare de Lyon, Paris',routeText:'Vom Novotel direkt zum Bahnhof. Ziel: spätestens 15:00 im Gare de Lyon sein.'},
    {type:'stop',time:'15:00',duration:60,title:'Am Gare de Lyon',icon:'🚄',fixed:true,subtitle:'Grosszügige Reserve vor der Abfahrt',destination:'Gare de Lyon, Paris',infoTitle:'Gare de Lyon – Abfahrt',info:`Euer Zug fährt um 16:22. Die frühe Ankunft am Bahnhof ist bewusst grosszügig geplant, damit ihr den richtigen Hallenbereich und später den Bahnsteig ohne Stress findet.`,look:'Bei französischen Fernzügen wird der genaue Bahnsteig oft erst relativ kurz vor Abfahrt angezeigt. Deshalb die Anzeigetafeln im Blick behalten.'},
    {type:'stop',time:'16:22',duration:10,title:'TGV-Abfahrt',icon:'🚄',fixed:true,subtitle:'FIXTERMIN',destination:'Gare de Lyon, Paris',infoTitle:'Au revoir Paris',info:`Damit endet euer Paris-Wochenende. Ihr habt sehr unterschiedliche Seiten der Stadt gesehen: Quartier Latin, Montmartre, Marais, Louvre, Haussmann-Paris, Champs-Élysées, Eiffelturm und das lokale 12. Arrondissement.`,look:'Im Zug kann jeder seinen persönlichen Lieblingsmoment der Reise nennen.'}
  ]
}
];
